version: "3.7"

services:
  server:
    build:
      context: nginx
      dockerfile: Dockerfile
    depends_on:
      - reverseproxy
      - app1
      - app2
      - app3
    ports:
    - "80:80"
    - "443:443"
    restart: always
    
  reverseproxy:
    container_name: reverseproxy
    build:
      context: src/YarpSamples.ReverseProxy
      dockerfile: Dockerfile
    expose:
      - "5000"
    restart: always
  
  app1:
    container_name: app1
    build:
      context: src/YarpSamples.Api
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:5001
    expose:
      - "5001"
    restart: always

  app2:
    container_name: app2
    build:
      context: src/YarpSamples.Api
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:5002
    expose:
      - "5002"
    restart: always

  app3:
    container_name: app3
    build:
      context: src/YarpSamples.Api
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:5003
    expose:
      - "5003"
    restart: always