version: "3.7"

services:
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
    - "80:80"
    - "443:443"
    restart: always
    
  reverseproxy:
    container_name: reverseproxy
    depends_on:
      - nginx
    build:
      context: src/YarpSamples.ReverseProxy
      dockerfile: Dockerfile
    expose:
      - "5000"
    restart: always
    
  api1:
    container_name: api1
    depends_on:
      - nginx
      - reverseproxy
    build:
      context: src/YarpSamples.Api
      dockerfile: Dockerfile
    expose:
      - "5001"
    restart: always
    
  api2:
    container_name: api2
    depends_on:
      - nginx
      - reverseproxy
    build:
      context: src/YarpSamples.Api
      dockerfile: Dockerfile
    expose:
      - "5002"
    restart: always
    
  api3:
    container_name: api3
    depends_on:
      - nginx
      - reverseproxy
    build:
      context: src/YarpSamples.Api
      dockerfile: Dockerfile
    expose:
      - "5003"
    restart: always