version: "3.7"

services:
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
    - "80:80"
    - "443:443"
    depends_on:
      - reverseproxy
      - api1
      - api2
      - api3
    restart: always
    
  reverseproxy:
    container_name: reverseproxy
    build:
      context: src/YarpSamples.ReverseProxy
      dockerfile: Dockerfile
    expose:
      - "5000"
    restart: always
    
  api1:
    container_name: api1
    build:
      context: src/YarpSamples.Api
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:443
    expose:
      - "5001"
    restart: always
    
  api2:
    container_name: api2
    build:
      context: src/YarpSamples.Api
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:443
    expose:
      - "5002"
    restart: always
    
  api3:
    container_name: api3
    build:
      context: src/YarpSamples.Api
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:443
    expose:
      - "5003"
    restart: always